### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-marketing-site#1]
- [x] Attach mock-up to issue
- https://invis.io/DYNCKZHBAGR first pass
- https://invis.io/U9NOWE6KCWJ second pass
- [x] Scaffold out components
- [x] Style out component
- [x] Scaffold and Style Testimonial Section
- [x] Responsive style pass (everything but brokerages section)
- [x] Add Carousel to Brokerages Section (and make sure it is responsive)
- [ ] Build models in Contentful
- [ ] Wire-up to Contentful
- [ ] Follow-up with marketing for final approval

**Comment by dillonmorris91** [comment]
![homepage](https://user-images.githubusercontent.com/27472341/44040573-80823f32-9ed0-11e8-88e1-06d9cc5803c8.jpg)
