### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-marketing-site#4]
- [x] Attach mock-up to issue 
- https://invis.io/BWNP1COGYED
- [x] Scaffold out template and components
- [x] Style out components
- [x] Build models in Contentful
- [x] Wire-up to Contentful
- [ ] Follow-up with marketing for final approval

Slugs:
`/elevateDMS`
`/elevateSP`
`/elevateIDX`
`/CRM`

**Comment by dillonmorris91** [comment]
![products](https://user-images.githubusercontent.com/27472341/44040736-db85d63c-9ed0-11e8-97cf-715e439c3533.jpg)
